name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push to github pages
      - uses: actions/checkout@v2
        name: Deploy
      - run: npm run deploy

